activos:
    path:     /
    defaults: { _controller: "escuelaBundle:activos:index" }

activos_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:activos:show" }

activos_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:activos:new" }

activos_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:activos:create" }
    requirements: { _method: post }

activos_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:activos:edit" }

activos_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:activos:update" }
    requirements: { _method: post|put }

activos_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:activos:delete" }
    requirements: { _method: post|delete }
