administracion:
    path:     /
    defaults: { _controller: "escuelaBundle:administracion:index" }

administracion_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:administracion:show" }

administracion_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:administracion:new" }

administracion_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:administracion:create" }
    requirements: { _method: post }

administracion_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:administracion:edit" }

administracion_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:administracion:update" }
    requirements: { _method: post|put }

administracion_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:administracion:delete" }
    requirements: { _method: post|delete }
