ajustes:
    path:     /
    defaults: { _controller: "escuelaBundle:ajustes:index" }

ajustes_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:ajustes:show" }

ajustes_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:ajustes:new" }

ajustes_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:ajustes:create" }
    requirements: { _method: post }

ajustes_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:ajustes:edit" }

ajustes_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:ajustes:update" }
    requirements: { _method: post|put }

ajustes_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:ajustes:delete" }
    requirements: { _method: post|delete }
