alumno:
    path:     /
    defaults: { _controller: "escuelaBundle:alumno:index" }

alumno_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:alumno:show" }

alumno_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:alumno:new" }

alumno_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:alumno:create" }
    requirements: { _method: post }
alumno_search:
    path:     /buscar
    defaults: { _controller: "escuelaBundle:alumno:search" }
    requirements: { _method: post }
alumno_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:alumno:edit" }

alumno_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:alumno:update" }
    requirements: { _method: post|put }

alumno_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:alumno:delete" }
    requirements: { _method: post|delete }
