anadirdetallesdelbanco:
    path:     /
    defaults: { _controller: "escuelaBundle:anadirDetallesDelBanco:index" }

anadirdetallesdelbanco_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:anadirDetallesDelBanco:show" }

anadirdetallesdelbanco_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:anadirDetallesDelBanco:new" }

anadirdetallesdelbanco_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:anadirDetallesDelBanco:create" }
    requirements: { _method: post }

anadirdetallesdelbanco_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:anadirDetallesDelBanco:edit" }

anadirdetallesdelbanco_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:anadirDetallesDelBanco:update" }
    requirements: { _method: post|put }

anadirdetallesdelbanco_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:anadirDetallesDelBanco:delete" }
    requirements: { _method: post|delete }
