articulotienda:
    path:     /
    defaults: { _controller: "escuelaBundle:articuloTienda:index" }

articulotienda_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:articuloTienda:show" }

articulotienda_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:articuloTienda:new" }

articulotienda_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:articuloTienda:create" }
    requirements: { _method: post }

articulotienda_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:articuloTienda:edit" }

articulotienda_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:articuloTienda:update" }
    requirements: { _method: post|put }

articulotienda_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:articuloTienda:delete" }
    requirements: { _method: post|delete }
