articulocategoria:
    path:     /
    defaults: { _controller: "escuelaBundle:articuloCategoria:index" }

articulocategoria_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:articuloCategoria:show" }

articulocategoria_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:articuloCategoria:new" }

articulocategoria_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:articuloCategoria:create" }
    requirements: { _method: post }

articulocategoria_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:articuloCategoria:edit" }

articulocategoria_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:articuloCategoria:update" }
    requirements: { _method: post|put }

articulocategoria_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:articuloCategoria:delete" }
    requirements: { _method: post|delete }
