asignaturas:
    path:     /
    defaults: { _controller: "escuelaBundle:asignaturas:index" }

asignaturas_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:asignaturas:show" }

asignaturas_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:asignaturas:new" }

asignaturas_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:asignaturas:create" }
    requirements: { _method: post }

asignaturas_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:asignaturas:edit" }

asignaturas_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:asignaturas:update" }
    requirements: { _method: post|put }

asignaturas_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:asignaturas:delete" }
    requirements: { _method: post|delete }
