cuotasinforme:
    path:     /
    defaults: { _controller: "escuelaBundle:cuotasInforme:index" }

cuotasinforme_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:cuotasInforme:show" }

cuotasinforme_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:cuotasInforme:new" }

cuotasinforme_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:cuotasInforme:create" }
    requirements: { _method: post }

cuotasinforme_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:cuotasInforme:edit" }

cuotasinforme_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:cuotasInforme:update" }
    requirements: { _method: post|put }

cuotasinforme_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:cuotasInforme:delete" }
    requirements: { _method: post|delete }
