detallesdecontacto:
    path:     /
    defaults: { _controller: "escuelaBundle:detallesDeContacto:index" }

detallesdecontacto_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:detallesDeContacto:show" }

detallesdecontacto_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:detallesDeContacto:new" }

detallesdecontacto_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:detallesDeContacto:create" }
    requirements: { _method: post }
detallesdecontacto_new_ajax:
    path:     /new_ajax
    defaults: { _controller: "escuelaBundle:detallesDeContacto:newAjax" }

detallesdecontacto_create_ajax:
    path:     /create_ajax
    defaults: { _controller: "escuelaBundle:detallesDeContacto:createAjax" }
    requirements: { _method: post }

detallesdecontacto_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:detallesDeContacto:edit" }
    
detallesdecontacto_edit_ajax:
    path:     /{id}/add
    defaults: { _controller: "escuelaBundle:detallesDeContacto:editAjax" }

detallesdecontacto_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:detallesDeContacto:update" }
    requirements: { _method: post|put }

detallesdecontacto_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:detallesDeContacto:delete" }
    requirements: { _method: post|delete }
