estructuradetarifas:
    path:     /
    defaults: { _controller: "escuelaBundle:estructuraDeTarifas:index" }

estructuradetarifas_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:estructuraDeTarifas:show" }

estructuradetarifas_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:estructuraDeTarifas:new" }

estructuradetarifas_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:estructuraDeTarifas:create" }
    requirements: { _method: post }

estructuradetarifas_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:estructuraDeTarifas:edit" }

estructuradetarifas_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:estructuraDeTarifas:update" }
    requirements: { _method: post|put }

estructuradetarifas_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:estructuraDeTarifas:delete" }
    requirements: { _method: post|delete }
