gastos:
    path:     /
    defaults: { _controller: "escuelaBundle:gastos:index" }

gastos_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:gastos:show" }

gastos_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:gastos:new" }

gastos_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:gastos:create" }
    requirements: { _method: post }

gastos_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:gastos:edit" }

gastos_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:gastos:update" }
    requirements: { _method: post|put }

gastos_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:gastos:delete" }
    requirements: { _method: post|delete }
