gestiondeexamenes:
    path:     /
    defaults: { _controller: "escuelaBundle:gestionDeExamenes:index" }

gestiondeexamenes_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:gestionDeExamenes:show" }

gestiondeexamenes_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:gestionDeExamenes:new" }

gestiondeexamenes_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:gestionDeExamenes:create" }
    requirements: { _method: post }

gestiondeexamenes_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:gestionDeExamenes:edit" }

gestiondeexamenes_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:gestionDeExamenes:update" }
    requirements: { _method: post|put }

gestiondeexamenes_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:gestionDeExamenes:delete" }
    requirements: { _method: post|delete }
