informefinanciero:
    path:     /
    defaults: { _controller: "escuelaBundle:informeFinanciero:index" }

informefinanciero_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:informeFinanciero:show" }

informefinanciero_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:informeFinanciero:new" }

informefinanciero_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:informeFinanciero:create" }
    requirements: { _method: post }

informefinanciero_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:informeFinanciero:edit" }

informefinanciero_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:informeFinanciero:update" }
    requirements: { _method: post|put }

informefinanciero_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:informeFinanciero:delete" }
    requirements: { _method: post|delete }
