nuevocliente:
    path:     /
    defaults: { _controller: "escuelaBundle:nuevoCliente:index" }

nuevocliente_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:nuevoCliente:show" }

nuevocliente_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:nuevoCliente:new" }

nuevocliente_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:nuevoCliente:create" }
    requirements: { _method: post }

nuevocliente_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:nuevoCliente:edit" }

nuevocliente_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:nuevoCliente:update" }
    requirements: { _method: post|put }

nuevocliente_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:nuevoCliente:delete" }
    requirements: { _method: post|delete }
