nuevacategoria:
    path:     /
    defaults: { _controller: "escuelaBundle:nuevaCategoria:index" }

nuevacategoria_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:nuevaCategoria:show" }

nuevacategoria_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:nuevaCategoria:new" }

nuevacategoria_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:nuevaCategoria:create" }
    requirements: { _method: post }

nuevacategoria_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:nuevaCategoria:edit" }

nuevacategoria_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:nuevaCategoria:update" }
    requirements: { _method: post|put }

nuevacategoria_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:nuevaCategoria:delete" }
    requirements: { _method: post|delete }
