pago:
    path:     /
    defaults: { _controller: "escuelaBundle:pago:index" }

pago_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:pago:show" }
pagopdf_show:
    path:     /{id}/pdf
    defaults: { _controller: "escuelaBundle:pago:showPdf" }

pago_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:pago:new" }

pago_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:pago:create" }
    requirements: { _method: post }

pago_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:pago:edit" }

pago_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:pago:update" }
    requirements: { _method: post|put }

pago_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:pago:delete" }
    requirements: { _method: post|delete }
