proveedores:
    path:     /
    defaults: { _controller: "escuelaBundle:proveedores:index" }

proveedores_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:proveedores:show" }

proveedores_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:proveedores:new" }

proveedores_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:proveedores:create" }
    requirements: { _method: post }

proveedores_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:proveedores:edit" }

proveedores_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:proveedores:update" }
    requirements: { _method: post|put }

proveedores_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:proveedores:delete" }
    requirements: { _method: post|delete }
