recibodesueldodelempleado:
    path:     /
    defaults: { _controller: "escuelaBundle:reciboDeSueldoDelEmpleado:index" }

recibodesueldodelempleado_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:reciboDeSueldoDelEmpleado:show" }

recibodesueldodelempleado_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:reciboDeSueldoDelEmpleado:new" }

recibodesueldodelempleado_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:reciboDeSueldoDelEmpleado:create" }
    requirements: { _method: post }

recibodesueldodelempleado_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:reciboDeSueldoDelEmpleado:edit" }

recibodesueldodelempleado_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:reciboDeSueldoDelEmpleado:update" }
    requirements: { _method: post|put }

recibodesueldodelempleado_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:reciboDeSueldoDelEmpleado:delete" }
    requirements: { _method: post|delete }
