resumendelotes:
    path:     /
    defaults: { _controller: "escuelaBundle:resumenDeLotes:index" }

resumendelotes_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:resumenDeLotes:show" }

resumendelotes_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:resumenDeLotes:new" }

resumendelotes_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:resumenDeLotes:create" }
    requirements: { _method: post }

resumendelotes_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:resumenDeLotes:edit" }

resumendelotes_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:resumenDeLotes:update" }
    requirements: { _method: post|put }

resumendelotes_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:resumenDeLotes:delete" }
    requirements: { _method: post|delete }
