role:
    path:     /
    defaults: { _controller: "escuelaBundle:role:index" }

role_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:role:show" }

role_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:role:new" }

role_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:role:create" }
    requirements: { _method: post }

role_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:role:edit" }

role_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:role:update" }
    requirements: { _method: post|put }

role_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:role:delete" }
    requirements: { _method: post|delete }
