seleccionempleadonomina:
    path:     /
    defaults: { _controller: "escuelaBundle:seleccionEmpleadoNomina:index" }

seleccionempleadonomina_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:seleccionEmpleadoNomina:show" }

seleccionempleadonomina_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:seleccionEmpleadoNomina:new" }

seleccionempleadonomina_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:seleccionEmpleadoNomina:create" }
    requirements: { _method: post }

seleccionempleadonomina_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:seleccionEmpleadoNomina:edit" }

seleccionempleadonomina_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:seleccionEmpleadoNomina:update" }
    requirements: { _method: post|put }

seleccionempleadonomina_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:seleccionEmpleadoNomina:delete" }
    requirements: { _method: post|delete }
