usuario:
    path:     /
    defaults: { _controller: "escuelaBundle:usuario:index" }

usuario_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:usuario:show" }

usuario_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:usuario:new" }

usuario_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:usuario:create" }
    requirements: { _method: post }

usuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:usuario:edit" }

usuario_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:usuario:update" }
    requirements: { _method: post|put }

usuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:usuario:delete" }
    requirements: { _method: post|delete }
