ventas:
    path:     /
    defaults: { _controller: "escuelaBundle:ventas:index" }

ventas_show:
    path:     /{id}/show
    defaults: { _controller: "escuelaBundle:ventas:show" }

ventas_new:
    path:     /new
    defaults: { _controller: "escuelaBundle:ventas:new" }

ventas_create:
    path:     /create
    defaults: { _controller: "escuelaBundle:ventas:create" }
    requirements: { _method: post }

ventas_edit:
    path:     /{id}/edit
    defaults: { _controller: "escuelaBundle:ventas:edit" }

ventas_update:
    path:     /{id}/update
    defaults: { _controller: "escuelaBundle:ventas:update" }
    requirements: { _method: post|put }

ventas_delete:
    path:     /{id}/delete
    defaults: { _controller: "escuelaBundle:ventas:delete" }
    requirements: { _method: post|delete }
