escuela:
    resource: "@escuelaBundle/Resources/config/routing.yml"
    prefix:   /
login:
    pattern:   /login
    defaults:  { _controller: escuelaBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
