<?php

namespace protecno\escuelaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class alumnoRepository extends EntityRepository
{

    public function findLike($anyKeyword) {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $concatFields = array(
            'a.nombre',
            'a.apellidoPaterno',
            'a.apellidoMaterno'
        );

        // Routine code. All fields will be separated by ' '.
        foreach ($concatFields as $field) {
            if (!isset($searchIn)) {
                $searchIn = $qb->expr()->concat($qb->expr()->literal(''), $field);
                continue;
            }
            else{
            $searchIn = $qb->expr()->concat(
                $searchIn,
                $qb->expr()->concat($qb->expr()->literal(' '), $field)
            );
         }
        }

        // Just use concat result to search in.
       // $anyKeyword = 'ego';
        $qb->select('d.id,'.$searchIn.' name')
         ->from('escuelaBundle:detallesDeContacto', 'd')
         ->innerjoin('d.alumno', 'a');
        $qb->add('where', $qb->expr()->like($searchIn, ':keyword'));
        $qb->setParameter('keyword', '%'. $anyKeyword .'%');
        //$query->setParameter('id', $id);
        $producto = $qb->getQuery()->getArrayResult();
       // echo '<pre>';print_r($producto);echo '</pre>';
        return $producto;
     }

}
