protecno\escuelaBundle\Entity\agregarFoto:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fotoNombre:
            type: string
            length: '100'
    manyToOne:
        categoriaFoto:
            targetEntity: protecno\escuelaBundle\Entity\categoriaFoto
            inversedBy: agregarFoto
        lotes:
            targetEntity: protecno\escuelaBundle\Entity\lotes
            inversedBy: agregarFoto         
    lifecycleCallbacks: {  }
