protecno\escuelaBundle\Entity\ajustes:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        identificacionBiometrica:
            type: string
            length: '100'
        habilitarFuncionesDeCorreoElectronico:
            type: boolean
    lifecycleCallbacks: {  }
