protecno\escuelaBundle\Entity\alumno:
    type: entity
    table: null
    repositoryClass: protecno\escuelaBundle\Entity\alumnoRepository
    fields:
        id: 
            type: integer
            id: true
            generator:
                strategy: AUTO
        noDeAdmision:
            type: integer
        fechaDeAdmision:
            type: datetime
        nombre:
            type: string
            length: '30'
        apellidoPaterno:
            type: string
            length: '30'
        apellidoMaterno:
            type: string
            length: '30'
        genero:
            type: string 
            length: '10'
        grupoSanguineo:
            type: string
            length: '15'
        lugarDeNacimiento:
            type: string
            length: '50'
        nacionalidad:
            type: string
            length: '50'
        fechaDeNacimiento:
            type: datetime 
    manyToOne:
        agrego: 
            targetEntity: protecno\escuelaBundle\Entity\anadirUsuario
            inversedBy: alumno
        modifico: 
            targetEntity: protecno\escuelaBundle\Entity\anadirUsuario
            inversedBy: alumno
        archivo:         
            targetEntity: protecno\escuelaBundle\Entity\archivo
            cascade: ["persist"]
    lifecycleCallbacks: {  }
