protecno\escuelaBundle\Entity\anadirTiposDeLicencia:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        dejaNombre:
            type: string
            length: '60'
        dejaCodigo:
            type: string
            length: '20'
        elNumeroMaximoDeLicencia:
            type: string
            length: '10'
        restablecerFecha:
            type: datetime
        estado:
            type: boolean
    lifecycleCallbacks: {  }
