protecno\escuelaBundle\Entity\anadirConfiguracionDeLaTarjetaBiblioteca:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        librosEmisionCondicionada:
            type: string
            length: '100'
        periodoDeTiempoDias:
            type: integer
    lifecycleCallbacks: {  }
