protecno\escuelaBundle\Entity\anadirIngreso:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        titulo:
            type: string
            length: '100'
        descripcion:
            type: string
            length: 255
        importe:
            type: integer
        fecha:
            type: datetime
    lifecycleCallbacks: {  }
