protecno\escuelaBundle\Entity\anadirUsuario:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombreDelUsuario:
            type: string
            length: '100'        
        password:
            type: string
            length: '125'       
        salt:
            type: string
            length: '125' 
        idPerfil:
            type: integer
    manyToMany:
        roles:
            targetEntity: protecno\escuelaBundle\Entity\role
            joinTable:
                name: user_role
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
