protecno\escuelaBundle\Entity\archivo:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: string
            length: '120'
        path:
            type: string
            length: 255
        imagen:
            type: string
            length: 255
        updated:
            type: datetime
    lifecycleCallbacks: {  }