protecno\escuelaBundle\Entity\archivo:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        descripcion:
            type: string
            length: 255
    manyToMany:
        lotes:
            targetEntity: protecno\escuelaBundle\Entity\lotes
            inversedBy: archivo     
    lifecycleCallbacks: {  }
