protecno\escuelaBundle\Entity\crearNuevaCategoriaFinanzas:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombreDeLaCategoria:
            type: string
            length: '100'
        descripcion:
            type: string
            length: 255
        esEstoBajoIngreso:
            type: boolean
    lifecycleCallbacks: {  }
