protecno\escuelaBundle\Entity\crearParticulares:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: '100'
        descripcion:
            type: string
            length: '100'
        crearUsando:
            type: boolean
        importe:
            type: integer
    manyToMany:
        categoriaHonorarios:
            targetEntity: protecno\escuelaBundle\Entity\categoriaHonorarios
            inversedBy: crearParticulares    
    lifecycleCallbacks: {  }
