protecno\escuelaBundle\Entity\cuotaColeccion:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        cuotaNombreDeLaColeccion:
            type: string
            length: '100'
        fechaDeInicio:
            type: datetime
            nullable: true
        fechaFinal:
            type: datetime
            nullable: true
        diasRecurrencia:
            type: integer
            nullable: true
        diaproximo:
            type: integer
            nullable: true
        monto:
            type: decimal
        tipo:
            type: integer
      
    lifecycleCallbacks: {  }
