protecno\escuelaBundle\Entity\curso:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombreDelCurso:
            type: string
            length: '50'
        nombreDeLaSeccion:
            type: string
            length: '100'
        activarLaSeleccionElectiva:
            type: boolean
            nullable: true
    manyToOne: 
        lotes:
            targetEntity: protecno\escuelaBundle\Entity\lotes
            inversedBy: curso         
    lifecycleCallbacks: {  }
