protecno\escuelaBundle\Entity\designacionDeClase:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: '100'
        marcas:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
