protecno\escuelaBundle\Entity\encuesta:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        titulo:
            type: string
            length: '100'
        descripcion:
            type: string
            length: 255
        respuesta:
            type: string
            length: 255
    manyToMany:
        lotes:
            targetEntity: protecno\escuelaBundle\Entity\lotes
            inversedBy: encuesta  
    lifecycleCallbacks: {  }
