protecno\escuelaBundle\Entity\eventos:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fechaDeInicio:
            type: datetime
        fechaFinal:
            type: datetime
        titulo:
            type: string
            length: '50'
        descripcion:
            type: string
            length: 255
    lifecycleCallbacks: {  }
