protecno\escuelaBundle\Entity\examenCursoSabio:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombreDelExamen:
            type: string
            length: '100'
    manyToMany:
        curso:
            targetEntity: protecno\escuelaBundle\Entity\curso
            inversedBy: examenCursoSabio
        lotes:
            targetEntity: protecno\escuelaBundle\Entity\lotes
            inversedBy: examenCursoSabio               
    lifecycleCallbacks: {  }
