protecno\escuelaBundle\Entity\finanzasCategoria:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: '100'
        descripcion:
            type: string
            length: '100'
        esEstoBajoIngreso:
            type: boolean
    lifecycleCallbacks: {  }
