protecno\escuelaBundle\Entity\generarFine:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        bellasNombre:
            type: string
            length: '100'
        diasDespuesDeLaFechaDeVencimiento:
            type: string
            length: '40'
        bellasCantidad:
            type: integer
        modo:
            type: boolean
    lifecycleCallbacks: {  }
