protecno\escuelaBundle\Entity\informeFinanciero:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fechaDeInicio:
            type: datetime
        fechaDeFinalizacion:
            type: datetime    
    lifecycleCallbacks: {  }
