protecno\escuelaBundle\Entity\mostrarTransacciones:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        seleccionarFechaDeInicio:
            type: datetime
        seleccioneFechaDeFinalizacion:
            type: datetime
    lifecycleCallbacks: {  }
