protecno\escuelaBundle\Entity\movimientoConectarse:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        seleccioneFecha:
            type: datetime
    lifecycleCallbacks: {  }
