protecno\escuelaBundle\Entity\nivelesDeClasificacion:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: '100'
        marcas:
            type: decimal
        numeroDeSujetos:
            type: integer
        considereTodosLosLotesAnteriores:
            type: boolean
    manyToMany:
        curso:
            targetEntity: protecno\escuelaBundle\Entity\curso
            inversedBy: nivelesDeClasificacion    
    lifecycleCallbacks: {  }
