protecno\escuelaBundle\Entity\nuevoHorario:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fechaDeInicio:
            type: datetime
        fechaFinal:
            type: datetime
    lifecycleCallbacks: {  }
