protecno\escuelaBundle\Entity\nuevoCliente:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombreDelCliente:
            type: string
            length: 255
        redirigidaURL:
            type: string
            length: '100'
        verificado:
            type: boolean
    lifecycleCallbacks: {  }
