protecno\escuelaBundle\Entity\proveedores:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombreDelProveedor:
            type: string
            length: '100'
        noContacto:
            type: integer
        direccion:
            type: string
            length: '100'
        noTin:
            type: integer
        region:
            type: string
            length: '100'
    manyToOne:
        tiposDeProveedor:
            targetEntity: protecno\escuelaBundle\Entity\tiposDeProveedor
            inversedBy: proveedores   
    lifecycleCallbacks: {  }
