protecno\escuelaBundle\Entity\resumenDeLotes:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        descripcion:
            type: string
            length: 255
    manyToMany:
        curso:
            targetEntity: protecno\escuelaBundle\Entity\curso
            inversedBy: resumenDeLotes 
        lotes:
            targetEntity: protecno\escuelaBundle\Entity\lotes
            inversedBy: resumenDeLotes         
    lifecycleCallbacks: {  }
