protecno\escuelaBundle\Entity\tipoDeTienda:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: '100'
        codigo:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
