protecno\escuelaBundle\Entity\verHojaDeSueldo:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        mes:
            type: datetime        
    manyToOne:
        anadirDepartamentoEmpleo:
            targetEntity: protecno\escuelaBundle\Entity\anadirDepartamentoEmpleo
            inversedBy: verHojaDeSueldo            
    lifecycleCallbacks: {  }
