escuelaBundle_archivo:
        resource: "@escuelaBundle/Resources/config/routing/archivo.yml"
        prefix:   /archivo
escuelaBundle_calendario:
        resource: "@escuelaBundle/Resources/config/routing/calendario.yml"
        prefix:   /calendario
escuelaBundle_academica:
        resource: "@escuelaBundle/Resources/config/routing/academica.yml"
        prefix:   /academica
escuelaBundle_administracion:
        resource: "@escuelaBundle/Resources/config/routing/administracion.yml"
        prefix:   /administracion 
escuelaBundle_administrarclientes:
        resource: "@escuelaBundle/Resources/config/routing/administrarclientes.yml"
        prefix:   /administrarclientes
escuelaBundle_administrarcursolote:
        resource: "@escuelaBundle/Resources/config/routing/administrarcursolote.yml"
        prefix:   /administrarcursolote                        
escuelaBundle_admisiondeestudiantes:
        resource: "@escuelaBundle/Resources/config/routing/admisiondeestudiantes.yml"
        prefix:   /admisiondeestudiantes                        
escuelaBundle_ajustes:
        resource: "@escuelaBundle/Resources/config/routing/ajustes.yml"
        prefix:   /ajustes
escuelaBundle_anadirlibro:
        resource: "@escuelaBundle/Resources/config/routing/anadirlibro.yml"
        prefix:   /anadirlibro
escuelaBundle_eventos:
        resource: "@escuelaBundle/Resources/config/routing/eventos.yml"
        prefix:   /eventos

escuelaBundle_agregarnoticia:
        resource: "@escuelaBundle/Resources/config/routing/agregarnoticia.yml"
        prefix:   /agregarnoticia

escuelaBundle_anadirempleadocategoria:
        resource: "@escuelaBundle/Resources/config/routing/anadirempleadocategoria.yml"
        prefix:   /anadirempleadocategoria
escuelaBundle_anadirdepartamentoempleo:
        resource: "@escuelaBundle/Resources/config/routing/anadirdepartamentoempleo.yml"
        prefix:   /anadirdepartamentoempleo
escuelaBundle_anadircategorianomina:
        resource: "@escuelaBundle/Resources/config/routing/anadircategorianomina.yml"
        prefix:   /anadircategorianomina
escuelaBundle_anadirempleadoposicion:
        resource: "@escuelaBundle/Resources/config/routing/anadirempleadoposicion.yml"
        prefix:   /anadirempleadoposicion
escuelaBundle_anadirempleadogrado:
        resource: "@escuelaBundle/Resources/config/routing/anadirempleadogrado.yml"
        prefix:   /anadirempleadogrado
escuelaBundle_anadirdetallesdelbanco:
        resource: "@escuelaBundle/Resources/config/routing/anadirdetallesdelbanco.yml"
        prefix:   /anadirdetallesdelbanco
escuelaBundle_nuevocliente:
        resource: "@escuelaBundle/Resources/config/routing/nuevocliente.yml"
        prefix:   /nuevocliente
escuelaBundle_nuevocliente:
        resource: "@escuelaBundle/Resources/config/routing/nuevocliente.yml"
        prefix:   /nuevocliente
escuelaBundle_nuevacategoria:
        resource: "@escuelaBundle/Resources/config/routing/nuevacategoria.yml"
        prefix:   /nuevacategoria
escuelaBundle_configuracionesgenerales:
        resource: "@escuelaBundle/Resources/config/routing/configuracionesgenerales.yml"
        prefix:   /configuracionesgenerales
escuelaBundle_anadircurso:
        resource: "@escuelaBundle/Resources/config/routing/anadircurso.yml"
        prefix:   /anadircurso
escuelaBundle_nuevogrupopin:
        resource: "@escuelaBundle/Resources/config/routing/nuevogrupopin.yml"
        prefix:   /nuevogrupopin
escuelaBundle_anadirqueja:
        resource: "@escuelaBundle/Resources/config/routing/anadirqueja.yml"
        prefix:   /anadirqueja
escuelaBundle_nivelesdeclasificacion:
        resource: "@escuelaBundle/Resources/config/routing/nivelesdeclasificacion.yml"
        prefix:   /nivelesdeclasificacion
escuelaBundle_examencursosabio:
        resource: "@escuelaBundle/Resources/config/routing/examencursosabio.yml"
        prefix:   /examencursosabio
escuelaBundle_gestiondeexamenes:
        resource: "@escuelaBundle/Resources/config/routing/gestiondeexamenes.yml"
        prefix:   /gestiondeexamenes
escuelaBundle_lotes:
        resource: "@escuelaBundle/Resources/config/routing/lotes.yml"
        prefix:   /lotes
escuelaBundle_curso:
        resource: "@escuelaBundle/Resources/config/routing/curso.yml"
        prefix:   /curso
escuelaBundle_comentariospersonalizados:
        resource: "@escuelaBundle/Resources/config/routing/comentariospersonalizados.yml"
        prefix:   /comentariospersonalizados
escuelaBundle_resumendelotes:
        resource: "@escuelaBundle/Resources/config/routing/resumendelotes.yml"
        prefix:   /resumendelotes
escuelaBundle_temporizaciondeclase:
        resource: "@escuelaBundle/Resources/config/routing/temporizaciondeclase.yml"
        prefix:   /temporizaciondeclase
escuelaBundle_tiempodeclase:
        resource: "@escuelaBundle/Resources/config/routing/tiempodeclase.yml"
        prefix:   /tiempodeclase
escuelaBundle_nuevohorario:
        resource: "@escuelaBundle/Resources/config/routing/nuevohorario.yml"
        prefix:   /nuevohorario
escuelaBundle_verhorarios:
        resource: "@escuelaBundle/Resources/config/routing/verhorarios.yml"
        prefix:   /verhorarios
escuelaBundle_seriesdetiempodeclasepordias:
        resource: "@escuelaBundle/Resources/config/routing/seriesdetiempodeclasepordias.yml"
        prefix:   /seriesdetiempodeclasepordias
escuelaBundle_horariosdelprofesor:
        resource: "@escuelaBundle/Resources/config/routing/horariosdelprofesor.yml"
        prefix:   /horariosdelprofesor
escuelaBundle_aulas:
        resource: "@escuelaBundle/Resources/config/routing/aulas.yml"
        prefix:   /aulas
escuelaBundle_carpeta:
        resource: "@escuelaBundle/Resources/config/routing/carpeta.yml"
        prefix:   /carpeta
escuelaBundle_carpetaprivilegiada:
        resource: "@escuelaBundle/Resources/config/routing/carpetaprivilegiada.yml"
        prefix:   /carpetaprivilegiada
escuelaBundle_carpetaespecificadelusuario:
        resource: "@escuelaBundle/Resources/config/routing/carpetaespecificadelusuario.yml"
        prefix:   /carpetaespecificadelusuario
escuelaBundle_categoriafoto:
        resource: "@escuelaBundle/Resources/config/routing/categoriafoto.yml"
        prefix:   /categoriafoto
escuelaBundle_agregarfoto:
        resource: "@escuelaBundle/Resources/config/routing/agregarfoto.yml"
        prefix:   /agregarfoto
escuelaBundle_nuevatarea:
        resource: "@escuelaBundle/Resources/config/routing/nuevatarea.yml"
        prefix:   /nuevatarea
escuelaBundle_encuesta:
        resource: "@escuelaBundle/Resources/config/routing/encuesta.yml"
        prefix:   /encuesta        
escuelaBundle_tiposdelicencia:
        resource: "@escuelaBundle/Resources/config/routing/tiposdelicencia.yml"
        prefix:   /tiposdelicencia
escuelaBundle_admisiondelempleado:
        resource: "@escuelaBundle/Resources/config/routing/admisiondelempleado.yml"
        prefix:   /admisiondelempleado
escuelaBundle_registrodeasistencia:
        resource: "@escuelaBundle/Resources/config/routing/registrodeasistencia.yml"
        prefix:   /registrodeasistencia
escuelaBundle_restableserajustes:
        resource: "@escuelaBundle/Resources/config/routing/restableserajustes.yml"
        prefix:   /restableserajustes
escuelaBundle_departamentorestableser:
        resource: "@escuelaBundle/Resources/config/routing/departamentorestableser.yml"
        prefix:   /departamentorestableser
escuelaBundle_seleccionempleadonomina:
        resource: "@escuelaBundle/Resources/config/routing/seleccionempleadonomina.yml"
        prefix:   /seleccionempleadonomina
escuelaBundle_recibodesueldodelempleado:
        resource: "@escuelaBundle/Resources/config/routing/recibodesueldodelempleado.yml"
        prefix:   /recibodesueldodelempleado
escuelaBundle_buscarempleados:
        resource: "@escuelaBundle/Resources/config/routing/buscarempleados.yml"
        prefix:   /buscarempleados
escuelaBundle_gestiondedatoscategorias:
        resource: "@escuelaBundle/Resources/config/routing/gestiondedatoscategorias.yml"
        prefix:   /gestiondedatoscategorias
escuelaBundle_categoriahonorarios:
        resource: "@escuelaBundle/Resources/config/routing/categoriahonorarios.yml"
        prefix:   /categoriahonorarios
escuelaBundle_crearparticulares:
        resource: "@escuelaBundle/Resources/config/routing/crearparticulares.yml"
        prefix:   /crearparticulares
escuelaBundle_generarmulta:
        resource: "@escuelaBundle/Resources/config/routing/generarmulta.yml"
        prefix:   /generarmulta
escuelaBundle_cuotacoleccion:
        resource: "@escuelaBundle/Resources/config/routing/cuotacoleccion.yml"
        prefix:   /cuotacoleccion
escuelaBundle_presentacioncuotasdelosestudiantes:
        resource: "@escuelaBundle/Resources/config/routing/presentacioncuotasdelosestudiantes.yml"
        prefix:   /presentacioncuotasdelosestudiantes
escuelaBundle_cuotasparticulares:
        resource: "@escuelaBundle/Resources/config/routing/cuotasparticulares.yml"
        prefix:   /cuotasparticulares
escuelaBundle_reportelotes:
        resource: "@escuelaBundle/Resources/config/routing/reportelotes.yml"
        prefix:   /reportelotes
escuelaBundle_cuotasinforme:
        resource: "@escuelaBundle/Resources/config/routing/cuotasinforme.yml"
        prefix:   /cuotasinforme
escuelaBundle_tema:
        resource: "@escuelaBundle/Resources/config/routing/tema.yml"
        prefix:   /tema
escuelaBundle_asignaturas:
        resource: "@escuelaBundle/Resources/config/routing/asignaturas.yml"
        prefix:   /asignaturas
escuelaBundle_administrarcuotas:
        resource: "@escuelaBundle/Resources/config/routing/administrarcuotas.yml"
        prefix:   /administrarcuotas
escuelaBundle_estructuradetarifas:
        resource: "@escuelaBundle/Resources/config/routing/estructuradetarifas.yml"
        prefix:   /estructuradetarifas
escuelaBundle_informecuotasestudiantes:
        resource: "@escuelaBundle/Resources/config/routing/informecuotasestudiantes.yml"
        prefix:   /informecuotasestudiantes
escuelaBundle_importacionescuotas:
        resource: "@escuelaBundle/Resources/config/routing/importacionescuotas.yml"
        prefix:   /importacionescuotas
escuelaBundle_honorariosinstantaneos:
        resource: "@escuelaBundle/Resources/config/routing/honorariosinstantaneos.yml"
        prefix:   /honorariosinstantaneos
escuelaBundle_finanzascategoria:
        resource: "@escuelaBundle/Resources/config/routing/finanzascategoria.yml"
        prefix:   /finanzascategoria
escuelaBundle_gastos:
        resource: "@escuelaBundle/Resources/config/routing/gastos.yml"
        prefix:   /gastos
escuelaBundle_gasto:
        resource: "@escuelaBundle/Resources/config/routing/gasto.yml"
        prefix:   /gasto
escuelaBundle_ingreso:
        resource: "@escuelaBundle/Resources/config/routing/ingreso.yml"
        prefix:   /ingreso
escuelaBundle_verhojadesueldo:
        resource: "@escuelaBundle/Resources/config/routing/verhojadesueldo.yml"
        prefix:   /verhojadesueldo
escuelaBundle_informefinanciero:
        resource: "@escuelaBundle/Resources/config/routing/informefinanciero.yml"
        prefix:   /informefinanciero
escuelaBundle_activos:
        resource: "@escuelaBundle/Resources/config/routing/activos.yml"
        prefix:   /activos
escuelaBundle_responsabilidad:
        resource: "@escuelaBundle/Resources/config/routing/responsabilidad.yml"
        prefix:   /responsabilidad
escuelaBundle_usuario:
        resource: "@escuelaBundle/Resources/config/routing/usuario.yml"
        prefix:   /usuario
escuelaBundle_tiendacategorias:
        resource: "@escuelaBundle/Resources/config/routing/tiendacategorias.yml"
        prefix:   /tiendacategorias
escuelaBundle_tipodetienda:
        resource: "@escuelaBundle/Resources/config/routing/tipodetienda.yml"
        prefix:   /tipodetienda
escuelaBundle_tienda:
        resource: "@escuelaBundle/Resources/config/routing/tienda.yml"
        prefix:   /tienda
escuelaBundle_articulocategoria:
        resource: "@escuelaBundle/Resources/config/routing/articulocategoria.yml"
        prefix:   /articulocategoria
escuelaBundle_tiposdeproveedor:
        resource: "@escuelaBundle/Resources/config/routing/tiposdeproveedor.yml"
        prefix:   /tiposdeproveedor
escuelaBundle_proveedores:
        resource: "@escuelaBundle/Resources/config/routing/proveedores.yml"
        prefix:   /proveedores
escuelaBundle_ordenesdecompra:
        resource: "@escuelaBundle/Resources/config/routing/ordenesdecompra.yml"
        prefix:   /ordenesdecompra
escuelaBundle_articulotienda:
        resource: "@escuelaBundle/Resources/config/routing/articulotienda.yml"
        prefix:   /articulotienda
escuelaBundle_ventas:
        resource: "@escuelaBundle/Resources/config/routing/ventas.yml"
        prefix:   /ventas        















